config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 283328 # Put your project id here

# If you want to run SQLFluff pre-commit hooks you'll need
# to set up a working profile it can use and list it below
profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["jaffle-data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ dbt.cast(dbt.current_timestamp(), 'datetime') }}"
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  jaffle_shop:
    +enabled: "{{ target.name != 'prod' }}"
    +schema: jaffle_shop_raw

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
